//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTrackerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alias
    {
        public Alias()
        {
            this.Players = new HashSet<Player>();
        }
    
        public string Name { get; set; }
        public long Id { get; set; }
        public Nullable<long> ClanId { get; set; }
    
        public virtual Clan Clan { get; set; }
        public virtual AliasRating AliasRating { get; set; }
        public virtual ICollection<Player> Players { get; set; }
    }
}
