//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTrackerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Aliases = new HashSet<Alias>();
            this.Games = new HashSet<Game>();
        }
    
        public string UniqueId { get; set; }
        public long Id { get; set; }
    
        public virtual ICollection<Alias> Aliases { get; set; }
        public virtual ICollection<Game> Games { get; set; }
    }
}
